// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#include "NativeMixerSource.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeMixerSource::NativeMixerSource() = default;

NativeMixerSource::~NativeMixerSource() = default;

auto NativeMixerSource::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeMixerSource>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.type)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.ssrc)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.volume)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.path)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.sample_rate)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.channel_num)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeMixerSource::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeMixerSource>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mType)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mSsrc)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mVolume)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPath)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mSampleRate)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mChannelNum))};
}

}  // namespace djinni_generated
