// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#pragma once

#include "djinni_support.hpp"
#include "mixer_config.hpp"

namespace djinni_generated {

class NativeMixerConfig final {
public:
    using CppType = ::audio_mixer::MixerConfig;
    using JniType = jobject;

    using Boxed = NativeMixerConfig;

    ~NativeMixerConfig();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeMixerConfig();
    friend ::djinni::JniClass<NativeMixerConfig>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/github/piasy/audio_mixer/MixerConfig") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;II)V") };
    const jfieldID field_mSources { ::djinni::jniGetFieldID(clazz.get(), "mSources", "Ljava/util/ArrayList;") };
    const jfieldID field_mOutputSampleRate { ::djinni::jniGetFieldID(clazz.get(), "mOutputSampleRate", "I") };
    const jfieldID field_mOutputChannelNum { ::djinni::jniGetFieldID(clazz.get(), "mOutputChannelNum", "I") };
};

}  // namespace djinni_generated
