// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#pragma once

#include "audio_mixer_api.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAudioMixerApi final : ::djinni::JniInterface<::audio_mixer::AudioMixerApi, NativeAudioMixerApi> {
public:
    using CppType = std::shared_ptr<::audio_mixer::AudioMixerApi>;
    using CppOptType = std::shared_ptr<::audio_mixer::AudioMixerApi>;
    using JniType = jobject;

    using Boxed = NativeAudioMixerApi;

    ~NativeAudioMixerApi();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAudioMixerApi>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAudioMixerApi>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAudioMixerApi();
    friend ::djinni::JniClass<NativeAudioMixerApi>;
    friend ::djinni::JniInterface<::audio_mixer::AudioMixerApi, NativeAudioMixerApi>;

};

}  // namespace djinni_generated
