// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#import "PYAAudioMixerApi.h"


int32_t const PYAAudioMixerApiMaxBufSize = 7680;

int32_t const PYAAudioMixerApiSampleSize = 2;
