// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#import "PYAMixerConfig.h"


int32_t const PYAMixerConfigMsPerBuf = 10;

@implementation PYAMixerConfig

- (nonnull instancetype)initWithSources:(nonnull NSArray<PYAMixerSource *> *)sources
                       outputSampleRate:(int32_t)outputSampleRate
                       outputChannelNum:(int32_t)outputChannelNum
{
    if (self = [super init]) {
        _sources = [sources copy];
        _outputSampleRate = outputSampleRate;
        _outputChannelNum = outputChannelNum;
    }
    return self;
}

+ (nonnull instancetype)mixerConfigWithSources:(nonnull NSArray<PYAMixerSource *> *)sources
                              outputSampleRate:(int32_t)outputSampleRate
                              outputChannelNum:(int32_t)outputChannelNum
{
    return [[self alloc] initWithSources:sources
                        outputSampleRate:outputSampleRate
                        outputChannelNum:outputChannelNum];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p sources:%@ outputSampleRate:%@ outputChannelNum:%@>", self.class, (void *)self, self.sources, @(self.outputSampleRate), @(self.outputChannelNum)];
}

@end
