// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#import <Foundation/Foundation.h>

@interface PYAMixerSource : NSObject
- (nonnull instancetype)initWithType:(int32_t)type
                                ssrc:(int32_t)ssrc
                              volume:(float)volume
                                path:(nonnull NSString *)path
                          sampleRate:(int32_t)sampleRate
                          channelNum:(int32_t)channelNum;
+ (nonnull instancetype)mixerSourceWithType:(int32_t)type
                                       ssrc:(int32_t)ssrc
                                     volume:(float)volume
                                       path:(nonnull NSString *)path
                                 sampleRate:(int32_t)sampleRate
                                 channelNum:(int32_t)channelNum;

@property (nonatomic, readonly) int32_t type;

@property (nonatomic, readonly) int32_t ssrc;

@property (nonatomic, readonly) float volume;

@property (nonatomic, readonly, nonnull) NSString * path;

@property (nonatomic, readonly) int32_t sampleRate;

@property (nonatomic, readonly) int32_t channelNum;

@end

extern int32_t const PYAMixerSourceTypeFile;
extern int32_t const PYAMixerSourceTypeRecord;
