// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#import "PYAMixerSource.h"


int32_t const PYAMixerSourceTypeFile = 1;

int32_t const PYAMixerSourceTypeRecord = 2;

@implementation PYAMixerSource

- (nonnull instancetype)initWithType:(int32_t)type
                                ssrc:(int32_t)ssrc
                              volume:(float)volume
                                path:(nonnull NSString *)path
                          sampleRate:(int32_t)sampleRate
                          channelNum:(int32_t)channelNum
{
    if (self = [super init]) {
        _type = type;
        _ssrc = ssrc;
        _volume = volume;
        _path = [path copy];
        _sampleRate = sampleRate;
        _channelNum = channelNum;
    }
    return self;
}

+ (nonnull instancetype)mixerSourceWithType:(int32_t)type
                                       ssrc:(int32_t)ssrc
                                     volume:(float)volume
                                       path:(nonnull NSString *)path
                                 sampleRate:(int32_t)sampleRate
                                 channelNum:(int32_t)channelNum
{
    return [(PYAMixerSource*)[self alloc] initWithType:type
                                                  ssrc:ssrc
                                                volume:volume
                                                  path:path
                                            sampleRate:sampleRate
                                            channelNum:channelNum];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p type:%@ ssrc:%@ volume:%@ path:%@ sampleRate:%@ channelNum:%@>", self.class, (void *)self, @(self.type), @(self.ssrc), @(self.volume), self.path, @(self.sampleRate), @(self.channelNum)];
}

@end
