// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#import "PYAMixerSource.h"
#include "mixer_source.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PYAMixerSource;

namespace djinni_generated {

struct MixerSource
{
    using CppType = ::audio_mixer::MixerSource;
    using ObjcType = PYAMixerSource*;

    using Boxed = MixerSource;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
