// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#import "PYAMixerConfig.h"
#include "mixer_config.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PYAMixerConfig;

namespace djinni_generated {

struct MixerConfig
{
    using CppType = ::audio_mixer::MixerConfig;
    using ObjcType = PYAMixerConfig*;

    using Boxed = MixerConfig;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
