// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#import "PYAMixerSource.h"
#import <Foundation/Foundation.h>

@interface PYAMixerConfig : NSObject
- (nonnull instancetype)initWithSources:(nonnull NSArray<PYAMixerSource *> *)sources
                       outputSampleRate:(int32_t)outputSampleRate
                       outputChannelNum:(int32_t)outputChannelNum;
+ (nonnull instancetype)mixerConfigWithSources:(nonnull NSArray<PYAMixerSource *> *)sources
                              outputSampleRate:(int32_t)outputSampleRate
                              outputChannelNum:(int32_t)outputChannelNum;

@property (nonatomic, readonly, nonnull) NSArray<PYAMixerSource *> * sources;

@property (nonatomic, readonly) int32_t outputSampleRate;

@property (nonatomic, readonly) int32_t outputChannelNum;

@end

/** stay the same as webrtc::AudioMixerImpl::kFrameDurationInMs */
extern int32_t const PYAMixerConfigMsPerBuf;
