// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#include "audio_mixer_api.hpp"  // my header
#include "mixer_config.hpp"
#include "mixer_source.hpp"

namespace audio_mixer {

int32_t constexpr AudioMixerApi::MAX_BUF_SIZE;

int32_t constexpr AudioMixerApi::SAMPLE_SIZE;

}  // namespace audio_mixer
