// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace audio_mixer {

struct MixerConfig;
struct MixerSource;

class AudioMixerApi {
public:
    virtual ~AudioMixerApi() {}

    static constexpr int32_t MAX_BUF_SIZE = 7680;

    static constexpr int32_t SAMPLE_SIZE = 2;

    static std::shared_ptr<AudioMixerApi> Create(const MixerConfig & config);

    virtual void UpdateVolume(int32_t ssrc, float volume) = 0;

    virtual bool AddSource(const MixerSource & source) = 0;

    virtual bool RemoveSource(int32_t ssrc) = 0;
};

}  // namespace audio_mixer
