// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#include "mixer_source.hpp"  // my header

namespace audio_mixer {

int32_t constexpr MixerSource::TYPE_FILE;

int32_t constexpr MixerSource::TYPE_RECORD;

}  // namespace audio_mixer
