// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#include "mixer_config.hpp"  // my header

namespace audio_mixer {

int32_t const MixerConfig::MS_PER_BUF = 10;

}  // namespace audio_mixer
