// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#include "mixer_source.hpp"  // my header

namespace audio_mixer {

int32_t const MixerSource::TYPE_FILE = 1;

int32_t const MixerSource::TYPE_RECORD = 2;

}  // namespace audio_mixer
