// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

package com.github.piasy.audio_mixer;

import java.util.ArrayList;

public final class MixerConfig {

    /** stay the same as webrtc::AudioMixerImpl::kFrameDurationInMs */
    public static final int MS_PER_BUF = 10;


    /*package*/ final ArrayList<MixerSource> mSources;

    /*package*/ final int mOutputSampleRate;

    /*package*/ final int mOutputChannelNum;

    public MixerConfig(
            ArrayList<MixerSource> sources,
            int outputSampleRate,
            int outputChannelNum) {
        this.mSources = sources;
        this.mOutputSampleRate = outputSampleRate;
        this.mOutputChannelNum = outputChannelNum;
    }

    public ArrayList<MixerSource> getSources() {
        return mSources;
    }

    public int getOutputSampleRate() {
        return mOutputSampleRate;
    }

    public int getOutputChannelNum() {
        return mOutputChannelNum;
    }

    @Override
    public String toString() {
        return "MixerConfig{" +
                "mSources=" + mSources +
                "," + "mOutputSampleRate=" + mOutputSampleRate +
                "," + "mOutputChannelNum=" + mOutputChannelNum +
        "}";
    }

}
