// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

package com.github.piasy.audio_mixer;

import java.util.ArrayList;

public final class MixerConfig {


    /*package*/ final ArrayList<MixerSource> mSources;

    /*package*/ final int mOutputSampleRate;

    /*package*/ final int mOutputChannelNum;

    /*package*/ final int mFrameDurationMs;

    public MixerConfig(
            ArrayList<MixerSource> sources,
            int outputSampleRate,
            int outputChannelNum,
            int frameDurationMs) {
        this.mSources = sources;
        this.mOutputSampleRate = outputSampleRate;
        this.mOutputChannelNum = outputChannelNum;
        this.mFrameDurationMs = frameDurationMs;
    }

    public ArrayList<MixerSource> getSources() {
        return mSources;
    }

    public int getOutputSampleRate() {
        return mOutputSampleRate;
    }

    public int getOutputChannelNum() {
        return mOutputChannelNum;
    }

    public int getFrameDurationMs() {
        return mFrameDurationMs;
    }

    @Override
    public String toString() {
        return "MixerConfig{" +
                "mSources=" + mSources +
                "," + "mOutputSampleRate=" + mOutputSampleRate +
                "," + "mOutputChannelNum=" + mOutputChannelNum +
                "," + "mFrameDurationMs=" + mFrameDurationMs +
        "}";
    }

}
